### PR TITLE
Update to Gulp 4

### PR DESCRIPTION
**Pull request by exoego**

### CODE REVIEW

**Comment by exoego** [comment]
Hmm, Travis is disabled on this repo?

**Comment by the-simian** [comment]
I don't recall explicitly disabling Travis, weird. I also haven't had a chance to test with gulp4, did you check this out? bummer you can't chain the tasks anymore

**Comment by the-simian** [comment]
Found out what was up with CI - Codeship was the service I was using and they 'disconnected' the repo on Dec31st (silently) so I just 'reconnected' it lets see if that makes CI work again. project is here: https://app.codeship.com/projects/42521

edit: looks like I set up travis as well https://travis-ci.org/github/the-simian/gulp-concat-filenames not sure why I did both I think I was comparing them at the time or something

**Comment by the-simian** [comment]
FYI here is your PR currently: https://travis-ci.org/github/the-simian/gulp-concat-filenames/builds/689953886

the PR build isn't passing, it seems

Edit: after a short investigation the `primordials is not defined` error is because node is too old, I need to upgrade node running CI to accommodate

**Pull request closed without merging**
